# -*- mode: ruby -*-
# vi: set ft=ruby :

ENV['VAGRANT_NO_PARALLEL'] = 'yes'

Vagrant.configure(2) do |config|

  config.vm.provision "shell", path: "bootstrap.sh"

  # Load Balancer Node
  config.vm.define "loadbalancer" do |lb|
    lb.vm.box = "generic/ubuntu2204"
    lb.vm.hostname = "loadbalancer"
    lb.vm.network "private_network", ip: "172.16.16.100"
    lb.vm.provider "virtualbox" do |v|
      v.name = "loadbalancer"
      v.memory = 2048
      v.cpus = 1
    end
  end
  
  # Number of Minio VMs
  MinioCount = 4

  # Configure Minio VMs
  (1..MinioCount).each do |i|
    config.vm.define "minio#{i}" do |minionode|
      minionode.vm.box = "generic/ubuntu2204"
      minionode.vm.hostname = "minio#{i}"
      minionode.vm.network "private_network", ip: "172.16.16.10#{i}"

      minionode.vm.provider "virtualbox" do |v|
        v.name = "minio#{i}"
        v.memory = 2048
        v.cpus = 2

        # Mount four disks for each VM
        (1..4).each do |disk_number|
          # Create disks using dedicated methods for specific storage controllers
          disk = "/data/virtualbox/vms/minio#{i}/disk#{disk_number}.vdi"
          unless File.exist? (disk)		    
                v.customize ['createhd', '--filename', disk, '--size', 20 * 1024]
          end
          v.customize ['storageattach', :id, '--storagectl', 'SATA Controller', '--port', disk_number, '--device', 0, '--type',  'hdd', '--medium', disk]

        end
      end
    end
  end
end
